Repository Automattic/dangermattic, pull requests merged in 2024-08, with the labels that each got.

#76 Bump Ruby dependencies
  Gemfile.lock
  danger-dangermattic.gemspec
  spec/spec_helper.rb
Labels: dependencies

#77 Create new releases with Rake
  CHANGELOG.md
  Rakefile
  rakelib/changelog_parser.rake
  rakelib/console.rake
  rakelib/git_helpers.rake
Labels: tooling

#78 Release 1.1.2 into trunk
  CHANGELOG.md
  Gemfile.lock
  lib/dangermattic/gem_version.rb
Labels: releases
